config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  get  '/cmind',   to: 'cminds#top'
  get  '/que1',    to: 'cminds#que1'
  get  '/que2',    to: 'cminds#que2'
  get  '/que3',    to: 'cminds#que3'
  get  '/que4',    to: 'cminds#que4'
  get  '/result',  to: 'cminds#result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/cmind.rb
class Cmind < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/cminds_controller.rb
class CmindsController < ApplicationController
  def top
    @cmind = Cmind.new
  end

  def que1
    @cmind = Cmind.new
  end

  def que2
    @que1 = params[:cmind][:que1]
    @cmind = Cmind.new
    @cmind.que1 = @que1
  end

  def que3
    @que1 = params[:que1]
    if params[:que2]
      @que2 = params[:que2]
    else
      @que2 = params[:cmind][:que2]
    end
    if params[:que4]
      @que4 = params[:que4]
    else
      @que4 = params[:cmind][:que4]
    end
    @cmind = Cmind.new
    @cmind.que1 = @que1
    @cmind.que2 = @que2
    @cmind.que4 = @que4
  end

  def que4
    @que1 = params[:que1]
    @que2 = params[:que2]
    @que3 = params[:cmind][:que3]
    @cmind = Cmind.new
    @cmind.que1 = @que1
    @cmind.que2 = @que2
    @cmind.que3 = @que3
  end

  def result
    @que1 = params[:que1]
    @que2 = params[:que2]
    @que3 = params[:cmind][:que3]
    @que4 = params[:que4]
    @cmind = Cmind.new
    @cmind.que1 = @que1
    @cmind.que2 = @que2
    @cmind.que3 = @que3
    @cmind.que4 = @que4

    if params[:no_ans]
      render :que4
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cminds_helper.rb
module CmindsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="blog_header">

  <h1>BLOG一覧</h1>

  <div class="blog_header_content">
    <!-- ブログヘッダー -->
    <h3>投稿数 <%= @blogs.count %></h3>
    <!-- 新規作成ボタン -->
    <div class="blog_create blog_btn">
      <%= link_to '新規作成', new_blog_path %>
    </div>
  </div>

</div>

<!-- ブログ記事一覧 -->
<div class="blogs">

  <% @blogs.each do |blog| %>

    <li>
      <div class="col-md-10">
        <!-- タイトル・ボディ -->
        <span class="blog_title"><%= blog.title %></span>
        <span class="blog_body"><%= blog.body %></span>
      </div>
      <div class="col-md-2">
        <!-- 詳細ボタン -->
        <div class="blog_show blog_btn">
          <%= link_to "詳 細", blog_path(blog) %>
        </div>
      </div>
    </li>

  <% end %>

</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/cminds/que1.html.erb
<% provide(:title, "que1") %>
<div class="cmind-form">

  <%= form_for(@cmind, url: que2_path, html: {method: 'GET'} ) do |f| %>
    <h2>今の「わたし、おれ、ぼく」</h2>
    <h2>つまりあなた自身の姿は、どのように見えますか？</h2>
    <%= f.text_area :que1 %>
    <%= f.submit "次へ" %>
  <% end %>

</div>

app/views/cminds/que2.html.erb
<% provide(:title, "que2") %>
<div class="cmind-form">

  <%= form_for(@cmind, url: que3_path, html: {method: 'GET'} ) do |f| %>
    <h2 style="margin-bottom: 225px;">じゃあ、明日からできることはなんですか？</h2>

    <%= hidden_field_tag :que1, @cmind.que1 %>

    <%= f.text_area :que2 %>
    <%= f.submit "次へ" %>
  <% end %>

</div>

app/views/cminds/que3.html.erb
<% provide(:title, "que3") %>

<div class="cmind-form">
  <%= form_for(@cmind, url: result_path, html: {method: 'GET'} ) do |f| %>

    <h2>一秒前のご自身より</h2>
    <h2>「今のあなた」は、前向きになれましたか？</h2>

    <%= hidden_field_tag :que1, @cmind.que1 %>
    <%= hidden_field_tag :que2, @cmind.que2 %>
    <%= hidden_field_tag :que4, @cmind.que4 %>

    <%= f.text_area :que3 %>

    <ul class="btn-box">
      <li ><%= f.submit "はい！！" %></li>
      <li ><%= f.submit "いや、まだ・・・", name: "no_ans" %></li>
      <li ><%= f.submit "いいえ！", name: "no_ans" %></li>
    </ul>
  <% end %>

</div>

app/views/cminds/que4.html.erb
<% provide(:title, "que4") %>
<div class="cmind-form">

  <%= form_for(@cmind, url: que3_path, html: {method: 'GET'} ) do |f| %>
    <h2 style="margin-bottom: 225px;">今からできることはなんですか？</h2>

    <%= hidden_field_tag :que1, @cmind.que1 %>
    <%= hidden_field_tag :que2, @cmind.que2 %>
    <%= hidden_field_tag :que3, @cmind.que3 %>

    <%= f.text_area :que4 %>
    <%= f.submit "次へ" %>
  <% end %>

</div>

app/views/cminds/result.html.erb
<% provide(:title, "result") %>
<div class="cmind-form">

  <%= form_for(@cmind, url: cmind_path, html: {method: 'GET'} ) do |f| %>
    <h2>あなたの「今」</h2>
    <h2>すごくいいです(＾◇＾)！！</h2>
    <h2>今の気持ちをみんなで共有しましょう♪</h2>

    <h3><%= @cmind.que1 %>
    <h3><%= @cmind.que2 %>
    <h3><%= @cmind.que4 %>
    <h3><%= @cmind.que3 %>

    <ul class="btn-box">
      <li><%= link_to 'Twitter', "https://twitter.com/share?url=#{request.url}&text=#{@cmind.que1}#{@cmind.que2}#{@cmind.que4}#{@cmind.que3}", class: 'twitter', title: 'Twitter', target: '_blank' %></li>
      <li><%= link_to 'Facebook', "https://www.facebook.com/sharer/sharer.php?u=#{request.url}&text=#{@cmind.que1}#{@cmind.que2}#{@cmind.que4}#{@cmind.que3}", class: 'facebook', title: 'Facebook', target: '_blank' %></li>
    </ul>

    <%= f.submit "TOPへ戻る" %>

  <% end %>

</div>

app/views/cminds/top.html.erb
<% provide(:title, "Top") %>
<div class="cmind-form">

  <%= form_for(@cmind, url: que1_path, html: {method: 'GET'} ) do |f| %>
    <h1>Changing the Mind</h1>
    <h2>一秒先の「今」へ踏み出そう</h2>
    <%= f.submit "スタート" %>
  <% end %>

</div>

<script>
  // 背景色変更
  $(function() {
    $('body').addClass('bg-cmind-top');
  });
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
 <!-- <ul>
    <li><%= link_to image_tag("twitter_icon.png", alt: "Twitter-Icon"), "#" %></li>
    <li><%= link_to image_tag("youtube_icon.png", alt: "Twitter-Icon"), "#" %></li>
  </ul>-->
  <p>yuji nakamura portfolio 2019</p>
</footer>

app/views/layouts/_header.html.erb
<header style="z-index:1000;">

  <!-- ヘッダー背景 -->
  <div class="nav-bg"></div>

  <!-- ロゴ -->
  <div class="logo" style="z-index:9999;">
    <ul>
      <li><%= link_to "新米父ちゃん", root_path %></li>
      <li><%= link_to "介護職からエンジニアへ", root_path %></li>
    </ul>
  </div>

  <!-- ヘッダーナビゲーション -->
  <div id="nav-header">
    <nav>
      <ul>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   help_path %></li>
        <li><%= link_to "Blog",   blogs_path %></li>
        <li><%= link_to "Contact",   '#' %></li>
        <li><%= link_to "cmind",   cmind_path %></li>
      </ul>
    </nav>
  </div>

  <!-- ハンバーガーメニューアイコン -->
  <div id="nav-toggle">
    <div>
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

   <!-- ハンバーガーメニューウインドウ -->
  <div id="nav-window">
    <nav>
      <ul>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   help_path %></li>
        <li><%= link_to "Brog",   '#' %></li>
        <li><%= link_to "Contact",   '#' %></li>
        <!--<li><%= link_to "Contact",   '#' %></li>-->
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    
    <!-- スマートフォン用設定 -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div id="contents">

  <!-- １番目のコンテンツ -->
  <div class="down-appear-trigger">
  <div class="normal-area down-appear">
      <div class="firstblock">
        <div class="bg1">
        <!--<div class="imgR">
        <%= image_tag "megane.png", alt: "megane" %>-->
        <h1>PORTFOLIO</h1>
        <h2>つくるものを通して<br>多くの人のお手伝いがしたい</h2>
      </div>
    </div>
  </div>

   <!-- スクロールダウン -->
  <div id="scroll_down_start">
      <a><span></span><p>scroll down</p></a>
  </div>



  <!-- ２番目のコンテンツ -->
  <div class="up-appear-trigger">
  <div class="non-background-area up-appear">
    <div class="white-block block2">
      <div id="scroll_down_end"></div>

      <div class="grid">
        <article class="main">
        </article>
        <section class="side">
          <ul>
            <h2>About</h2>
            <li>１９８７年１２月１６日生まれ</li>
            <li>介護業界に１０年勤める</li>
            <li>素敵な奥さんと結婚して、子ども２人授かる</li>
            <li>エンジニアという仕事に出会う</li>
            <li>家族との時間、お金、今の抱えている閉塞感</li>
            <li>エンジニアになれば、全て叶えられる</li>
            <li>30代転職</li>
            <li>決死の覚悟で取り組みます！</li>
       </section>
      </div>

      <!-- <div class="imgR">
        <%= image_tag "megane.png", alt: "megane" %>
        <h1>About</h1>
        <h2>介護業界に約10年勤務</h2>
        <h2>身長差１５ｃｍの凸凹夫婦</h2>
        <h2>一姫二太郎の２児の父ちゃん</h2>
        <h2>オンラインでプログラミング学習</h2>
        <h2>未経験でwebエンジニアの世界へ（予定）</h2>
      </div> -->
    </div>
  </div>


  <!-- 領域全体 -->
  <section class="non-background-area grid-block">

    <!-- グリッド表示 -->
    <div class="container grid-container">

      <!-- 記事1 -->
      <div class="grid-content grid-block-1">
        <!-- イメージ -->
        <div class="grid-content-image hover:shadow-raised hover:translateY-2px transition">
          <%= image_tag "mind.jpg", alt: "Harry" %>
          <!-- テキスト -->
          <div class="grid-content-text">
            <h3><%= "changing the mind".truncate(20) %></h3>
            <p><span><%= "自分自身の問いかけでポジティブな思考へ".truncate(32) %></span></p>
          </div>
        </div>
      </div>

      <!-- 記事2 -->
      <div class="grid-content grid-block-2">
        <!-- イメージ -->
        <div class="grid-content-image hover:shadow-raised hover:translateY-2px transition">
          <%= image_tag "climd.jpg", alt: "Harry" %>
          <!-- テキスト -->
          <div class="grid-content-text">
            <h3><%= "railsチュートリアル完走".truncate(20) %></h3>
            <p><span><%= "Coming Soon".truncate(32) %></span></p>
          </div>
        </div>
      </div>
      <!-- 記事3 -->
      <div class="grid-content grid-block-3">
        <!-- イメージ -->
        <div class="grid-content-image hover:shadow-raised hover:translateY-2px transition">
          <%= image_tag "parenting.jpg", alt: "Harry" %>
          <!-- テキスト -->
          <div class="grid-content-text">
            <h3><%= "新米父ちゃん子育て論".truncate(13) %></h3>
            <p><span><%= "Coming Soon".truncate(32) %></span></p>
          </div>
        </div>
      </div>

      <!-- 記事4 -->
      <div class="grid-content grid-block-4">
        <!-- イメージ -->
        <div class="grid-content-image hover:shadow-raised hover:translateY-2px transition">
          <%= image_tag "change.jpg", alt: "Harry" %>
          <!-- テキスト -->
          <div class="grid-content-text">
            <h3><%= "転職活動について".truncate(13) %></h3>
            <p><span><%= "Coming Soon".truncate(32) %></span></p>
          </div>
        </div>
      </div>

    
  </section>


    <!-- ３番目のコンテンツ -->
  <div class="left-slide-trigger">
  <div class="normal-area left-slide">
    <div class="white-block block2">
      <div class="imgL">
        <%= image_tag "megane.png", alt: "megane" %>
        <h1>contact</h1>
        <p>自分の日々の行動をツイートしていますので<br>良ければ見てください</p>
        <ul>
          <li><%= link_to image_tag("twitter_icon.png", alt: "Twitter-Icon"), "#" %></li>
        </ul>
      </div>  
    </div>
  </div>

  <!-- ４番目のコンテンツ 
  <div class="right-slide-trigger">
  <div class="normal-area right-slide">
    <div class="normal-block">
      <div class="imgL">
        <%= image_tag "megane.png", alt: "megane" %>
        <h1>ピコン！<br>とひらめく力！！</h1>
        <p>楽しくプログラミングする、まったり、ゆっくりな小動物、ハリー教授です！！</p>
      </div>  
    </div>
  </div>-->

</div>

<script>
  // *================================================
  // * スクロールダウン
  // *================================================
  var position = $("#scroll_down_end").offset().top -100;

  $("#scroll_down_start").click(function(){

    $("html,body").animate({
        scrollTop : position
    }, {
        queue : false
    });
  });
</script>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>